/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipaint;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author yaseen
 */
public class DrawingJFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    Engine engine = new Engine();
    public DrawingJFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LinePanal = new javax.swing.JPanel();
        PositionLabel = new javax.swing.JLabel();
        LengthLabel = new javax.swing.JLabel();
        PositionTextField = new javax.swing.JTextField();
        LengthTextField = new javax.swing.JTextField();
        CirclePanel = new javax.swing.JPanel();
        PositionCirLabel = new javax.swing.JLabel();
        RadiusLabel = new javax.swing.JLabel();
        PositionCirTextField = new javax.swing.JTextField();
        RadiusTextField = new javax.swing.JTextField();
        RectanglePanel = new javax.swing.JPanel();
        PositionRecLabel = new javax.swing.JLabel();
        LengthRecLabel = new javax.swing.JLabel();
        PositionTextField7 = new javax.swing.JTextField();
        LengthTextField8 = new javax.swing.JTextField();
        WedthRecLabel = new javax.swing.JLabel();
        WidthTextField9 = new javax.swing.JTextField();
        SquarePanel3 = new javax.swing.JPanel();
        PositionLabel6 = new javax.swing.JLabel();
        SideLabel7 = new javax.swing.JLabel();
        PositionTextField5 = new javax.swing.JTextField();
        SideTextField6 = new javax.swing.JTextField();
        ColorizePanel6 = new javax.swing.JPanel();
        ColorButton7 = new javax.swing.JButton();
        FillColorButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        EllipsPanel2 = new javax.swing.JPanel();
        WedthEllipsLabel1 = new javax.swing.JLabel();
        WidthTextField10 = new javax.swing.JTextField();
        PositionEllipsLabel1 = new javax.swing.JLabel();
        LengthLabel1 = new javax.swing.JLabel();
        PositionTextField8 = new javax.swing.JTextField();
        LengthTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        ColorizeButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        CircleButton = new javax.swing.JButton();
        LinesegmantButton = new javax.swing.JButton();
        SquareButton = new javax.swing.JButton();
        RectangleButton = new javax.swing.JButton();
        DrawingPanl = new javax.swing.JPanel()
        {
            Engine engine =new Engine();
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                ArrayList <Shapes> shapes = engine.getShapes();
                for (Shapes shape:shapes)
                {
                    if (shape instanceof Circle) {
                        Circle c = (Circle) shape;
                        c.draw(g);

                    } else if (shape instanceof Rectangle) {
                        Rectangle rect = (Rectangle) shape;
                        rect.draw(g);

                    }
                    else if(shape instanceof Linesegment)
                    {
                        Linesegment line =(Linesegment) shape;
                        line.draw(g);

                    }
                    else if(shape instanceof Square)
                    {
                        Square square =(Square) shape;
                        square.draw(g);

                    }
                    else if(shape instanceof Ellips)
                    {
                        Ellips ellips =(Ellips) shape;
                        ellips.draw(g);

                    }

                }
            }

        }

        ;
        EllipsButton = new javax.swing.JButton();
        RedoButton = new javax.swing.JButton();
        UndoButton = new javax.swing.JButton();

        PositionLabel.setText("Position");

        LengthLabel.setText("Length");

        javax.swing.GroupLayout LinePanalLayout = new javax.swing.GroupLayout(LinePanal);
        LinePanal.setLayout(LinePanalLayout);
        LinePanalLayout.setHorizontalGroup(
            LinePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinePanalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(LinePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionLabel)
                    .addComponent(LengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(LinePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PositionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(LengthTextField))
                .addGap(66, 66, 66))
        );
        LinePanalLayout.setVerticalGroup(
            LinePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LinePanalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(LinePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionLabel)
                    .addComponent(PositionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(LinePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LengthLabel))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        LinePanal.getAccessibleContext().setAccessibleName("LineSegmant Properties");

        {

        }
        CirclePanel.setToolTipText("Circle Properties");

        PositionCirLabel.setText("Position");

        RadiusLabel.setText("Radius");

        PositionCirTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionCirTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CirclePanelLayout = new javax.swing.GroupLayout(CirclePanel);
        CirclePanel.setLayout(CirclePanelLayout);
        CirclePanelLayout.setHorizontalGroup(
            CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirclePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadiusLabel)
                    .addComponent(PositionCirLabel))
                .addGap(92, 92, 92)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionCirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        CirclePanelLayout.setVerticalGroup(
            CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirclePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PositionCirLabel)
                    .addComponent(PositionCirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadiusLabel)
                    .addComponent(RadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        CirclePanel.getAccessibleContext().setAccessibleDescription("");
        CirclePanel.getAccessibleContext().setAccessibleParent(jLabel1);

        PositionRecLabel.setText("Position");

        LengthRecLabel.setText("Length");

        WedthRecLabel.setText("Width");

        javax.swing.GroupLayout RectanglePanelLayout = new javax.swing.GroupLayout(RectanglePanel);
        RectanglePanel.setLayout(RectanglePanelLayout);
        RectanglePanelLayout.setHorizontalGroup(
            RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanglePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WedthRecLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PositionRecLabel)
                    .addComponent(LengthRecLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PositionTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(LengthTextField8)
                    .addComponent(WidthTextField9))
                .addGap(66, 66, 66))
        );
        RectanglePanelLayout.setVerticalGroup(
            RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanglePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionRecLabel)
                    .addComponent(PositionTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LengthRecLabel))
                .addGap(56, 56, 56)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WedthRecLabel)
                    .addComponent(WidthTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        PositionLabel6.setText("Position");

        SideLabel7.setText("Side");

        javax.swing.GroupLayout SquarePanel3Layout = new javax.swing.GroupLayout(SquarePanel3);
        SquarePanel3.setLayout(SquarePanel3Layout);
        SquarePanel3Layout.setHorizontalGroup(
            SquarePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SquarePanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(SquarePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionLabel6)
                    .addComponent(SideLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addGroup(SquarePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PositionTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(SideTextField6))
                .addGap(66, 66, 66))
        );
        SquarePanel3Layout.setVerticalGroup(
            SquarePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SquarePanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(SquarePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionLabel6)
                    .addComponent(PositionTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(SquarePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SideTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SideLabel7))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        ColorButton7.setText("Color");
        ColorButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorButton7ActionPerformed(evt);
            }
        });

        FillColorButton8.setText("Fill Color");
        FillColorButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillColorButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ColorizePanel6Layout = new javax.swing.GroupLayout(ColorizePanel6);
        ColorizePanel6.setLayout(ColorizePanel6Layout);
        ColorizePanel6Layout.setHorizontalGroup(
            ColorizePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColorizePanel6Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(ColorizePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ColorButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FillColorButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        ColorizePanel6Layout.setVerticalGroup(
            ColorizePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColorizePanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ColorButton7)
                .addGap(74, 74, 74)
                .addComponent(FillColorButton8)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        WedthEllipsLabel1.setText("Width");

        PositionEllipsLabel1.setText("Position");

        LengthLabel1.setText("Highet");

        javax.swing.GroupLayout EllipsPanel2Layout = new javax.swing.GroupLayout(EllipsPanel2);
        EllipsPanel2.setLayout(EllipsPanel2Layout);
        EllipsPanel2Layout.setHorizontalGroup(
            EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EllipsPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WedthEllipsLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PositionEllipsLabel1)
                    .addComponent(LengthLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addGroup(EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PositionTextField8)
                    .addComponent(LengthTextField9)
                    .addComponent(WidthTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        EllipsPanel2Layout.setVerticalGroup(
            EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EllipsPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionEllipsLabel1)
                    .addComponent(PositionTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LengthLabel1))
                .addGap(56, 56, 56)
                .addGroup(EllipsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WedthEllipsLabel1)
                    .addComponent(WidthTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vector Drawing Application");

        jLabel1.setText("Select Shape");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Shape", " ", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        ColorizeButton.setText("Colorize");
        ColorizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorizeButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        CircleButton.setText("Circle");
        CircleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleButtonActionPerformed(evt);
            }
        });

        LinesegmantButton.setText("Line Segmant");
        LinesegmantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinesegmantButtonActionPerformed(evt);
            }
        });

        SquareButton.setText("Square");
        SquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareButtonActionPerformed(evt);
            }
        });

        RectangleButton.setText("Rectangle");
        RectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectangleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DrawingPanlLayout = new javax.swing.GroupLayout(DrawingPanl);
        DrawingPanl.setLayout(DrawingPanlLayout);
        DrawingPanlLayout.setHorizontalGroup(
            DrawingPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        DrawingPanlLayout.setVerticalGroup(
            DrawingPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );

        EllipsButton.setText("Ellips");
        EllipsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EllipsButtonActionPerformed(evt);
            }
        });

        RedoButton.setText("Redo");
        RedoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedoButtonActionPerformed(evt);
            }
        });

        UndoButton.setText("Undo");
        UndoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ColorizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(RedoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UndoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DrawingPanl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EllipsButton)
                .addGap(18, 18, 18)
                .addComponent(CircleButton)
                .addGap(18, 18, 18)
                .addComponent(LinesegmantButton)
                .addGap(18, 18, 18)
                .addComponent(RectangleButton)
                .addGap(18, 18, 18)
                .addComponent(SquareButton)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SquareButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RectangleButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EllipsButton)
                        .addComponent(CircleButton)
                        .addComponent(LinesegmantButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DrawingPanl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ColorizeButton)
                            .addComponent(DeleteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RedoButton)
                            .addComponent(UndoButton))
                        .addGap(107, 107, 107))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:   

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private Shapes getSelectedShape() {
        String selectedItem = (String) jComboBox4.getSelectedItem();
        if (selectedItem == null) {
            return null;
        }
        String[] parts = selectedItem.split(" ");
        String shapeType = parts[0];
        int index = Integer.parseInt(parts[1]) - 1;
        switch (shapeType) {
            case "Circle":
                return engine.getCircle(index);
            case "Rectangle":
                return engine.getRectangle(index);
            case "Ellips":
                return engine.getEllips(index);
            case "Square":
                return engine.getSquare(index);
            case "Linesegment":
                return engine.getLinesegment(index);
            // أضف حالات أخرى لبقية الأشكال
            default:
                return null;
        }
    }
    private void CircleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, CirclePanel, "Circle Properties", JOptionPane.INFORMATION_MESSAGE);
        if (PositionCirTextField.getText().isEmpty() || RadiusTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!PositionCirTextField.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] position = PositionCirTextField.getText().split(",");
        if (position.length != 2) {
            JOptionPane.showMessageDialog(null, "invalid input for Position", "Error", JOptionPane.ERROR_MESSAGE);
        }
        int[] coordinates = new int[2];
        coordinates[0] = Integer.parseInt(position[0]);
        coordinates[1] = Integer.parseInt(position[1]);
        Point p = new Point();
        p.x = coordinates[0];
        p.y = coordinates[1];
        double radius = Double.parseDouble(RadiusTextField.getText());

        Circle circle = new Circle(radius, p);
        Graphics graphics = DrawingPanl.getGraphics();
        circle.draw(graphics);
        engine.addShape(circle);
        int circount = engine.getCountCir();
        jComboBox4.addItem("Circle" + circount);
    }//GEN-LAST:event_CircleButtonActionPerformed

    private void LinesegmantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinesegmantButtonActionPerformed

        JOptionPane.showMessageDialog(null, LinePanal, "Circle Properties", JOptionPane.INFORMATION_MESSAGE);
        if (PositionTextField.getText().isEmpty() || LengthTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!PositionTextField.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] position = PositionTextField.getText().split(",");
        if (position.length != 2) {
            JOptionPane.showMessageDialog(null, "invalid input for Position", "Error", JOptionPane.ERROR_MESSAGE);
        }
        int[] coordinates = new int[2];
        coordinates[0] = Integer.parseInt(position[0].trim());
        coordinates[1] = Integer.parseInt(position[1].trim());
        Point p = new Point();
        p.x = coordinates[0];
        p.y = coordinates[1];
        double Length = Double.parseDouble(LengthTextField.getText());

        Graphics graphics = DrawingPanl.getGraphics();
        Linesegment Line = new Linesegment(Length, p);

        Line.draw(graphics);
        engine.addShape(Line);
        int linecount = engine.getCountLine();
        jComboBox4.addItem("LineSegment " + linecount);        // TODO add your handling code here:
    }//GEN-LAST:event_LinesegmantButtonActionPerformed

    private void SquareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareButtonActionPerformed
        JOptionPane.showMessageDialog(null, SquarePanel3, "Circle Properties", JOptionPane.INFORMATION_MESSAGE);
        if (PositionTextField5.getText().isEmpty() || SideTextField6.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!PositionTextField5.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] position = PositionTextField5.getText().split(",");
        if (position.length != 2) {
            JOptionPane.showMessageDialog(null, "not true input", "error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int[] coordinates = new int[2];
        coordinates[0] = Integer.parseInt(position[0].trim());
        coordinates[1] = Integer.parseInt(position[1].trim());
        Point p = new Point();
        p.x = coordinates[0];
        p.y = coordinates[1];
        double Length = Double.parseDouble(SideTextField6.getText());

        Square square = new Square(Length, p);
        Graphics graphics = DrawingPanl.getGraphics();
        square.draw(graphics);
        engine.addShape(square);
        int squarecount = engine.getCountSqu();
        jComboBox4.addItem("Square" + squarecount);          // TODO add your handling code here:

    }//GEN-LAST:event_SquareButtonActionPerformed

    private void RectangleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectangleButtonActionPerformed
        JOptionPane.showMessageDialog(null, RectanglePanel, "Rectangle Properties", JOptionPane.INFORMATION_MESSAGE);
        if (PositionTextField7.getText().isEmpty() || LengthTextField8.getText().isEmpty() || WidthTextField9.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!PositionTextField7.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] position = PositionTextField7.getText().split(",");
        if (position.length != 2) {
            JOptionPane.showMessageDialog(null, "invalid input for Position", "Error", JOptionPane.ERROR_MESSAGE);
        }
        int[] coordinates = new int[2];
        coordinates[0] = Integer.parseInt(position[0].trim());
        coordinates[1] = Integer.parseInt(position[1].trim());
        Point p = new Point();
        p.x = coordinates[0];
        p.y = coordinates[1];
        double Length = Double.parseDouble(LengthTextField8.getText());
        double Width = Double.parseDouble(WidthTextField9.getText());

        Rectangle rectangle = Rectangle.CreateRectangle(Length, Width, p);
        Graphics graphics = DrawingPanl.getGraphics();
        rectangle.draw(graphics);
        engine.addShape(rectangle);
        if (Length == Width) {
            int sqrcount = engine.getCountSqu();
            jComboBox4.addItem("Square" + sqrcount);
        } else {
            int rectscount = engine.getCountRec();
            jComboBox4.addItem("Rectangle" + rectscount);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_RectangleButtonActionPerformed

    private void ColorizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorizeButtonActionPerformed
        JOptionPane.showMessageDialog(null, ColorizePanel6, "Choose", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:

    }//GEN-LAST:event_ColorizeButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
Shapes selectedShape=getSelectedShape();
if(selectedShape!=null)
{  
engine.removeShape(selectedShape);
jComboBox4.removeItem(jComboBox4.getSelectedItem());
engine.refresh(DrawingPanl.getGraphics());
}
else
{
    JOptionPane.showMessageDialog(null, "error no item selected", "error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void PositionCirTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionCirTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionCirTextFieldActionPerformed

    private void ColorButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorButton7ActionPerformed
        // TODO add your handling code here:
        Shapes selectedShape = getSelectedShape();
    if (selectedShape != null) {
        Color color = JColorChooser.showDialog(null, "Choose a Border Color", Color.BLACK);
        selectedShape.setColor(color);
        engine.refresh(DrawingPanl.getGraphics());
    } else {
        JOptionPane.showMessageDialog(null, "No shape selected", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ColorButton7ActionPerformed

    private void FillColorButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillColorButton8ActionPerformed
        // TODO add your handling code here:
        Shapes selectedShape = getSelectedShape();
    if (selectedShape != null) {
        Color color = JColorChooser.showDialog(null, "Choose a Fill Color", Color.BLACK);
        selectedShape.setFillColor(color);
        engine.refresh(DrawingPanl.getGraphics());
    } else {
        JOptionPane.showMessageDialog(null, "No shape selected", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_FillColorButton8ActionPerformed

    private void UndoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoButtonActionPerformed

    private void EllipsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EllipsButtonActionPerformed
        JOptionPane.showMessageDialog(null, EllipsPanel2, "Rectangle Properties", JOptionPane.INFORMATION_MESSAGE);
        if (PositionTextField8.getText().isEmpty() || LengthTextField9.getText().isEmpty() || WidthTextField10.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some fields are empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!PositionTextField8.getText().contains(",")) {
            JOptionPane.showMessageDialog(null, "Invalid input", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] position = PositionTextField8.getText().split(",");
        if (position.length != 2) {
            JOptionPane.showMessageDialog(null, "invalid input for Position", "Error", JOptionPane.ERROR_MESSAGE);
        }
        int[] coordinates = new int[2];
        coordinates[0] = Integer.parseInt(position[0].trim());
        coordinates[1] = Integer.parseInt(position[1].trim());
        Point p = new Point();
        p.x = coordinates[0];
        p.y = coordinates[1];
        double Length = Double.parseDouble(LengthTextField9.getText());
        double Width = Double.parseDouble(WidthTextField10.getText());

        Ellips ellips = Ellips.CreateEllips(Length, Width, p);
        Graphics graphics = DrawingPanl.getGraphics();
        ellips.draw(graphics);
        engine.addShape(ellips);

        if (Length == Width) {
            int circount = engine.getCountCir();
            jComboBox4.addItem("Circle" + circount);
        } else {
            int ellipscount = engine.getCountEllips();
            jComboBox4.addItem("Ellips" + ellipscount);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EllipsButtonActionPerformed

    private void RedoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RedoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DrawingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CircleButton;
    private javax.swing.JPanel CirclePanel;
    private javax.swing.JButton ColorButton7;
    private javax.swing.JButton ColorizeButton;
    private javax.swing.JPanel ColorizePanel6;
    private javax.swing.JButton DeleteButton;
    public static javax.swing.JPanel DrawingPanl;
    private javax.swing.JButton EllipsButton;
    private javax.swing.JPanel EllipsPanel2;
    private javax.swing.JButton FillColorButton8;
    private javax.swing.JLabel LengthLabel;
    private javax.swing.JLabel LengthLabel1;
    private javax.swing.JLabel LengthRecLabel;
    private javax.swing.JTextField LengthTextField;
    private javax.swing.JTextField LengthTextField8;
    private javax.swing.JTextField LengthTextField9;
    private javax.swing.JPanel LinePanal;
    private javax.swing.JButton LinesegmantButton;
    private javax.swing.JLabel PositionCirLabel;
    private javax.swing.JTextField PositionCirTextField;
    private javax.swing.JLabel PositionEllipsLabel1;
    private javax.swing.JLabel PositionLabel;
    private javax.swing.JLabel PositionLabel6;
    private javax.swing.JLabel PositionRecLabel;
    private javax.swing.JTextField PositionTextField;
    private javax.swing.JTextField PositionTextField5;
    private javax.swing.JTextField PositionTextField7;
    private javax.swing.JTextField PositionTextField8;
    private javax.swing.JLabel RadiusLabel;
    private javax.swing.JTextField RadiusTextField;
    private javax.swing.JButton RectangleButton;
    private javax.swing.JPanel RectanglePanel;
    private javax.swing.JButton RedoButton;
    private javax.swing.JLabel SideLabel7;
    private javax.swing.JTextField SideTextField6;
    private javax.swing.JButton SquareButton;
    private javax.swing.JPanel SquarePanel3;
    private javax.swing.JButton UndoButton;
    private javax.swing.JLabel WedthEllipsLabel1;
    private javax.swing.JLabel WedthRecLabel;
    private javax.swing.JTextField WidthTextField10;
    private javax.swing.JTextField WidthTextField9;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
